"""Generate metamodel.js (compact DEXPI 2.0.1 Core+Plant class table) for in-browser validation."""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import validate  # loads tools/spec/Core.xml + Plant.xml into validate.classes

KIND = {"CompositionProperty": "C", "ReferenceProperty": "R", "DataProperty": "D"}
out = {}
for name, c in validate.classes.items():
    out[name] = [1 if c["abstract"] else 0, c["supers"],
                 {p: [KIND[k], t, lo, up] for p, (k, t, lo, up) in c["props"].items()}]
dst = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "metamodel.js")
with open(dst, "w", encoding="utf-8") as f:
    f.write("// Generated by tools/build_metamodel.py from DEXPI 2.0.1 Core.xml + Plant.xml (CC BY 4.0, DEXPI).\n")
    f.write("// Format: class -> [isAbstract, superTypes[], {property: [kind C|R|D, type, lower, upper|null]}]\n")
    f.write("window.DEXPI_METAMODEL={version:'2.0.1',classes:" + json.dumps(out, separators=(",", ":")) + "};\n")
print(f"{len(out)} classes -> {os.path.getsize(dst)//1024} KB")
