"""Wrap the default sample XML in a <script>-loadable file so index.html can open it from file://
(browsers block fetch() there). Usage: python tools/build_sample_js.py [samples/<file>.xml]"""
import json, os, sys

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(root, "samples", "reference_pid.dexpi.xml")
dst = os.path.splitext(src)[0] + ".js"
with open(src, encoding="utf-8") as f:
    xml = f.read()
with open(dst, "w", encoding="utf-8") as f:
    f.write("// Generated by tools/build_sample_js.py from " + os.path.basename(src) + " (DEXPI reference P&ID, CC BY 4.0).\n")
    f.write("window.DEXPI_SAMPLE=" + json.dumps({"name": os.path.basename(src), "xml": xml}) + ";\n")
print(f"{dst} ({os.path.getsize(dst) // 1024} KB)")
